config/routes.rb
Rails.application.routes.draw do
  root 'votes#new'

  resources :jokes, only: [] do
    resources :votes, only: [:new, :create]
  end

  get 'jokes/votes/goodbye' => 'votes#goodbye', as: :goodbye_votes
end

app/models/joke.rb
class Joke < ActiveRecord::Base
	has_many :votes
	validates :content, presence: true

	def self.next_unvoted_joke(voted_jokes)
		Joke.where.not(id: voted_jokes).first
	end

	def increase_like
		update_attributes(like: like + 1)
	end

	def increase_dislike
		update_attributes(dislike: dislike + 1)
	end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :joke
	validates :joke, presence: true
	validates :like, inclusion: [true, false]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/joke_tracker.rb
module JokeTracker
	extend ActiveSupport::Concern

	def mark_voted_joke(joke_id)
		voted_jokes << joke_id
	end

	def voted_jokes
		session[:voted_jokes] ||= []
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	include JokeTracker
	before_action :check_voted_joke, only: [:new]

	def new
		@vote = current_joke.votes.new
	end

	def create
		@vote = current_joke.votes.build(vote_params)
		if @vote.save
			update_current_joke
			mark_voted_joke(current_joke.id)
			redirect_to_next_unvoted_joke
		else
			render :new
		end
	end

	def goodbye
	end

	private

		def joke_id
			params[:joke_id]
		end

		def vote_params
			params.require(:vote).permit(:like)
		end

		def current_joke
			if params[:joke_id].present?
				Joke.find(params[:joke_id])
			else
				Joke.first
			end
		end

		def update_current_joke
			if params[:vote][:like].to_s == "true"
				current_joke.increase_like
			else
				current_joke.increase_dislike
			end
		end

		def redirect_to_next_unvoted_joke
			next_joke = Joke.next_unvoted_joke(voted_jokes)
			if next_joke.present?
				redirect_to new_joke_vote_path(next_joke.id)
			else
				redirect_to goodbye_votes_url
			end
		end

		def check_voted_joke
			redirect_to_next_unvoted_joke if voted_jokes.include? current_joke.id
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jokee</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/votes/goodbye.html.slim
h1 That's all the jokes for today! Come back another day!

app/views/votes/new.html.slim
- joke = @vote.joke
= joke.content

= simple_form_for @vote, url: joke_votes_url(joke.id) do |f|
	= f.input :like,
		as: :radio_buttons,
		label: false
	= f.button :submit